name: Create Release

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip files
        run: |
          zip -j -r adb-bin-linux-ia32.zip linux/ia32
          zip -j -r adb-bin-linux-x64.zip linux/x64
          zip -j -r adb-bin-mac-ia32.zip mac/ia32
          zip -j -r adb-bin-mac-x64.zip mac/x64
          zip -j -r adb-bin-win-ia32.zip win/ia32
          zip -j -r adb-bin-win-x64.zip win/x64

      - name: Create release and upload assets
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            adb-bin-linux-ia32.zip
            adb-bin-linux-x64.zip
            adb-bin-mac-ia32.zip
            adb-bin-mac-x64.zip
            adb-bin-win-ia32.zip
            adb-bin-win-x64.zip
